name: Alpha Service

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Alpha Service Test
    runs-on: ubuntu-18.04
    steps:
      - name: Run Unit Tests
        run:
          yarn workspace alpha run test

