name: Beta Service

on:
  push:
    paths:
    - '/packages/beta/*'

jobs:
  test:
    name: Beta Service Test
    runs-on: ubuntu-18.04
    steps:
      - name: Build
        run:
          yarn install 

      - name: Say Hello
        run:
          echo Beta

